BinaryStudioAcademy/bsa-winter-2023-2024-trackmates

apps/frontend/src/index.tsx, apps/frontend/src/libs/components/components.ts, apps/frontend/src/libs/components/protected-route/protected-route.tsx, apps/frontend/src/modules/auth/slices/auth.slice.ts
=> feat: add protected routing tm-15

apps/frontend/src/libs/components/sidebar/styles.module.css
=> fix: nav bar position change tm-114

apps/backend/src/libs/modules/server-application/base-server-application-api.ts
=> fix(backend): fix swagger issue in deployed application tm-128

apps/frontend/src/libs/components/courses/styles.module.css, apps/frontend/src/libs/components/header/styles.module.css, apps/frontend/src/libs/components/sidebar/styles.module.css, apps/frontend/src/pages/overview/libs/components/welcome-section-header/styles.module.css, apps/frontend/src/pages/overview/libs/components/welcome-section-header/welcome-section-header.tsx, apps/frontend/src/pages/overview/styles.module.css
Mobile
Tablets
Desktop:
P.S. The name for test was generated by AI
=> fix(frontend): fix mobile design for header and welcome section, button label tm-61

apps/frontend/eslint.config.js, apps/frontend/src/pages/auth/auth.tsx
Redirect the user to the "Overview" page after successful registration/authorization
=> fix(frontend): add public route for signin signup tm-145

apps/frontend/src/libs/components/sidebar/sidebar.tsx, apps/frontend/src/libs/components/sidebar/styles.module.css, apps/frontend/src/pages/overview/styles.module.css
**Replace sidebar with bottom menu on PWA app**
=> fix(frontend): sidebar mobile pwa tm-139

apps/frontend/src/pages/friends/libs/components/friend-list/styles.module.css, apps/frontend/src/pages/friends/styles.module.css
Breakpoints:
- 320px
- 480px
- 768px
=> feat(frontend): Add friends page mobile responsiveness tm-157

apps/frontend/src/libs/components/auth-wrapper/styles.module.css, apps/frontend/src/libs/components/sidebar/styles.module.css
=> fix(frontend): sidebar is scrollable on the overview and friends pages tm-219

apps/backend/src/modules/auth/auth.controller.ts, apps/backend/src/modules/chat-messages/chat-message.controller.ts, apps/backend/src/modules/chats/chat.controller.ts, apps/backend/src/modules/course-sections/course-section.controller.ts, apps/backend/src/modules/courses/course.controller.ts, apps/backend/src/modules/files/file.controller.ts, apps/backend/src/modules/friends/friend.controller.ts, apps/backend/src/modules/user-courses/user-course.controller.ts, apps/backend/src/modules/users/user.controller.ts, apps/backend/src/modules/vendors/vendor.controller.ts
=> feat(backend): organize controllers on Swagger into corresponding sections tm-218

apps/frontend/src/pages/profile/profile.tsx, apps/frontend/src/pages/profile/styles.module.css
=> feat(frontend): add change photo button to the my profile page tm-273

apps/backend/src/modules/chats/chat.service.ts, apps/backend/src/modules/chats/chats.ts, apps/backend/src/modules/friends/friend.repository.ts, apps/backend/src/modules/friends/friends.ts, package-lock.json, packages/shared/src/libs/enums/exception-message.enum.ts
=> fix(backend/shared): remove mutual followers check tm-290

apps/frontend/src/libs/components/button/button.tsx, apps/frontend/src/libs/components/button/styles.module.css, apps/frontend/src/libs/components/course/course.tsx
=> feat(frontend): make add button disable after adding the course tm-291

apps/frontend/src/pages/profile/profile.tsx
=> feat(frontend): Make the "Nickname" field on the "My Profile" page to display the updated placeholder tm-305

apps/frontend/src/pages/friends/libs/components/friend/friend.tsx, apps/frontend/src/pages/user/user.tsx
=> feat(frontend): Make the "Following" buttons on the user components on the "Friends" page and on the users' pages outlined buttons tm-317

apps/frontend/src/pages/user/styles.module.css
=> fix(frontend): fix align vertically elemetns on the friend page tm-326

apps/backend/src/modules/activities/activity.repository.ts
=> fix(backend): likes shouldn't reset coments count tm-159

apps/backend/src/modules/courses/course.repository.ts, apps/backend/src/modules/courses/course.service.ts
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/1119d1a7-1c78-4f53-bd34-831435e44a1e
=> fix(backend): fix bug with course progress tm-415

apps/frontend/src/libs/components/course/course.tsx, apps/frontend/src/modules/courses/slices/courses.slice.ts
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/f7d494f2-d4c4-4d5c-8df9-84aa9fa0353a
=> fix(frontend): add disabling button in each section tm-374

apps/frontend/src/pages/profile/profile.tsx, apps/frontend/src/pages/profile/styles.module.css
=> feat(frontend): My profile - mobile responsiveness tm-452

apps/frontend/src/modules/user-courses/slices/actions.ts, apps/frontend/src/modules/user-courses/slices/user-courses.slice.ts, apps/frontend/src/pages/user/styles.module.css, apps/frontend/src/pages/user/user.tsx
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/8f310e42-fbb5-4863-a493-ff638adb152f
=> feat(frontend): add pagination for friend profile page tm-471

apps/frontend/src/modules/friends/slices/friends.slice.ts, apps/frontend/src/pages/friends/friends.tsx, apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
=> fix(frontend): The "Follow" / "Following" buttons on user components are not updated on the new tab after following / unfollowing the users tm-444

apps/frontend/src/libs/components/button/styles.module.css, apps/frontend/src/libs/components/circular-progress/styles.module.css, apps/frontend/src/libs/components/course/styles.module.css, apps/frontend/src/libs/components/pagination/libs/components/pagination-item/styles.module.css, apps/frontend/src/libs/components/sidebar/styles.module.css, apps/frontend/src/pages/feed/libs/components/feed-activity/styles.module.css, apps/frontend/src/pages/friends/libs/components/friend/styles.module.css, apps/frontend/src/pages/notifications/styles.module.css
=> feat(frontend): add transitions during changing the state of the element tm-492

apps/frontend/src/pages/user/styles.module.css
=> feat(frontend): add friend profile mobile responsiveness tm-453

apps/frontend/src/pages/notifications/libs/components/notification-list-item/notification-list-item.tsx, apps/frontend/src/pages/notifications/libs/components/notification-list-item/styles.module.css, apps/frontend/src/pages/notifications/libs/components/notification-list/styles.module.css, apps/frontend/src/pages/notifications/styles.module.css
=> feat(frontend): Notifications - mobile responsiveness tm-508

apps/frontend/src/libs/components/search-bar/libs/enums/enums.ts, apps/frontend/src/libs/components/search-bar/search-bar.tsx, apps/frontend/src/libs/enums/enums.ts, apps/frontend/src/libs/enums/query-parameter-name.enum.ts, apps/frontend/src/pages/notifications/libs/enums/enums.ts, apps/frontend/src/pages/notifications/notifications.tsx, apps/frontend/src/pages/overview/overview.tsx
- Notification:
- Courses:
- Change page
=> feat(frontend): search by url tm-470

apps/frontend/src/libs/modules/store/middlewares/notifications-socket.middleware.ts, apps/frontend/src/modules/user-notifications/slices/user-notifications.slice.ts, apps/frontend/src/pages/notifications/notifications.tsx
Incoming notifications are presented within the currently active filter
=> feat(frontend): incoming notification presentation tm-498

apps/frontend/src/pages/user/styles.module.css
Fixed the indents between the header, the "Back" button, the green block and the "Courses" label.
=> fix(frontend): friend profile responsiveness tm-453

apps/frontend/src/pages/feed/libs/components/feed-activity/feed-activity.tsx, apps/frontend/src/pages/feed/libs/components/feed-activity/styles.module.css
Added transitions to the opening comments on the Activities page
=> feat(frontend): add transitions to comments tm-541

apps/frontend/src/assets/css/scaffolding.css, apps/frontend/src/pages/chats/libs/components/chat-sidebar/styles.module.css, apps/frontend/src/pages/chats/libs/components/chat/styles.module.css
- Chrome, Opera, Edge, Safari:
- Firefox:
=> feat(frontend): customized scrollbar everywhere tm-560

apps/frontend/src/pages/auth/auth.tsx
=> fix(frontend): The "Sign In | TrackMates" page title is shown after trying going back from "Overview" page tm-566

apps/frontend/src/pages/notifications/notifications.tsx
=> fix(frontend): Real-time notifications don't appear on the "All" tab of the "Notifications" page tm-571

apps/frontend/src/pages/management/libs/components/courses-tab/libs/components/course-columns/course-columns.tsx
=> feat(frontend): change vendors title to logo tm-558

apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
=> fix(frontend): The Back button does not navigate to the previous page on the Friend's profile page tm-535

apps/frontend/src/libs/enums/app-title.enum.ts, apps/frontend/src/pages/not-found/not-found.tsx, apps/frontend/src/pages/user/user.tsx
=> fix(frontend): Add titles for the Friend profile and Not found pages tm-601

apps/frontend/src/libs/components/checkbox/styles.module.css, apps/frontend/src/pages/course-progress-comparison/styles.module.css, apps/frontend/vite.config.ts
=> fix(frontend): Compare progress mobile responsiveness tm-602

apps/frontend/src/pages/chats/libs/components/chat-message/styles.module.css
=> fix(frontend): message word break tm-576

apps/frontend/src/pages/management/libs/components/courses-tab/libs/constants/courses-table-headers.constant.ts, apps/frontend/src/pages/management/libs/components/courses-tab/libs/enums/courses-table-header.enum.ts, apps/frontend/src/pages/management/libs/components/groups-tab/groups-tab.tsx, apps/frontend/src/pages/management/libs/components/groups-tab/libs/constants/groups-table-headers.constant.ts, apps/frontend/src/pages/management/libs/components/groups-tab/libs/enums/groups-table-header.enum.ts, apps/frontend/src/pages/management/libs/components/groups-tab/libs/maps/groups-header-to-property-name.map.ts, apps/frontend/src/pages/management/libs/components/users-tab/libs/constants/users-table-headers.constant.ts, apps/frontend/src/pages/management/libs/components/users-tab/libs/enums/users-table-header.enum.ts, apps/frontend/src/pages/management/libs/components/users-tab/libs/maps/users-header-to-property-name.map.ts, apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
Added "Actions" title to the Edit/Delete column to all tabs on the Management page
=> feat(frontend): add actions title to button column of tables on the Management page tm-557

apps/backend/src/modules/friends/friend.service.ts, apps/backend/src/modules/notifications/notification.repository.ts, apps/backend/src/modules/notifications/notification.service.ts
=> feat(backend): delete notification when user unffollow current user tm-608

apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
=> feat(frontend): User image on the Chats page should navigate to the Friend profile page tm-635

apps/backend/.env.example, apps/backend/package.json, apps/backend/src/libs/modules/config/base-config.module.ts, apps/backend/src/libs/modules/config/libs/types/environment-schema.type.ts, apps/backend/src/libs/modules/mail/mail.module.ts, apps/backend/src/libs/modules/mail/mail.ts, apps/backend/src/modules/files/file.service.ts, apps/backend/src/modules/files/files.ts, package-lock.json, readme.md
=> feat(backend): aws ses for mails tm-611

apps/backend/src/modules/friends/friend.service.ts, apps/backend/src/modules/notifications/notification.repository.ts, apps/backend/src/modules/notifications/notification.service.ts
=> feat(backend): the previously send notification should not display if user refollow that user tm-608

apps/frontend/src/libs/components/header/styles.module.css
=> fix(frontend): Counters on the Notifications and Chats icons on the header are not clickable tm-658

apps/frontend/src/pages/feed/libs/components/comment-card/styles.module.css
=> fix(frontend): stick crown to avatar tm-702

apps/frontend/src/pages/auth/styles.module.css, apps/frontend/src/pages/overview/libs/components/welcome-section-header/styles.module.css, apps/frontend/src/pages/profile/styles.module.css
=> fix(frontend): layout issues on mobile devices tm-692

apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
=> fix(frontend): update profile picture tm-712

apps/frontend/src/libs/components/empty-page-placeholder/styles.module.css
=> fix(frontend): placeholders width and position tm-695

apps/frontend/src/libs/components/header/header.tsx, apps/frontend/src/pages/profile/profile.tsx
=> fix(frontend): update profile picture tm-720
